export enum Status {
  HTTP_OK = 200,
  HTTP_ERROR = 420,
  HTTP_NOT_FOUND = 404,
  HTTP_UNPROCESSABLE_ENTITY = 422,
  USER_INVALID_CREDENTIALS = 2,
  USER_ALREADY_CONNECTED = 3,
  USER_DOESNT_EXISTS = 4,
  ALREADY_EXISTS = 10
}

