export const TYPES =  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        AuthenticationController: Symbol("AuthenticationController"),
        AuthenticationRouter: Symbol("AuthenticationRouter"),
        ChannelController: Symbol("ChannelController"),
        AlbumController: Symbol("AlbumController"),
        AlbumRouter: Symbol("AlbumRouter"),
        ChannelRouter: Symbol("ChannelRouter"),
        ChannelSocketService: Symbol("ChannelSocketService"),
        ConnectionSocketService: Symbol("ConnectionSocketService"),
        DrawingSocketService: Symbol("DrawingSocketService"),
        DrawingRouter: Symbol("DrawingRouter"),
        DrawingController: Symbol("DrawingController"),
        DrawingDatabaseService: Symbol("DrawingDatabaseService"),
        SocketService: Symbol("SocketService"),
        AuthenticationDatabaseService: Symbol("AuthenticationDatabaseService"),
        ChannelDatabaseService: Symbol("ChannelDatabaseService"),
        ProfileDatabaseService: Symbol("ProfileDatabaseService"),
        AlbumDatabaseService: Symbol("AlbumDatabaseService"),
        ProfileController: Symbol("ProfileController"),
        ProfileRouter: Symbol("ProfileRouter"),
        LobbyDatabaseService: Symbol("LobbyDatabaseService"),
        LobbyController: Symbol("LobbyController"),
        LobbyRouter: Symbol("LobbyRouter"),
        LobbySocketService: Symbol("LobbySocketService")
};